### ISSUE TITLE
Is multilingualization possible?

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [giskonsulenten/EasyTemplatePrint-for-Qgis3#1]
Nice to meet you.
I am always looking forward to working with you.
Unfortunately, however, I am Japanese and many people around me are not comfortable with English.
Is it possible to make it multilingual?
I suppose I could convert the UI by myself, but I would like to publish it through here if possible.
Translation will be done here.

**Comment by giskonsulenten** [comment]
HI

I am flattered that my plugin has reach Japan. Unfortunately I do not have
time to make it multilingual at the moment. But you are welcome to do the
work and inform me if you do.

Best regards

Med venlig hilsen

Jesper Jøker Eg

Mobiltlf.: +45 61 72 75 57 <+45%2061%2072%2075%2057>

LinkedIn-profil:  Jesper Jøker Eg
<https://dk.linkedin.com/in/jesper-j%C3%B8ker-eg-6588a359>
E-mail:  ***@***.***

Web:  https://www.giskonsulenten.dk/


Den lør. 18. jun. 2022 kl. 01.47 skrev yamamoto ryuzo <
***@***.***>:

**Comment by yamamoto-ryuzo** [comment]
Thank you for your reply.
I am about 30 years behind in my knowledge of the program, but would appreciate it when you are ready to pulls.

**Comment by yamamoto-ryuzo** [comment]
This is the first time I have created a TS file by myself.
Is this correct?

https://github.com/yamamoto-ryuzo/EasyTemplatePrint-for-Qgis3/tree/master/i18n

**Comment by yamamoto-ryuzo** [comment]
I made a PULL request anyway.
https://github.com/giskonsulenten/EasyTemplatePrint-for-Qgis3/pull/2
